# Generated by Django 6.0.2 on 2026-02-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
